apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-helmrelease.yaml
  - helmrelease.yaml
# Note: postgres.yaml is unused - using Bitnami PostgreSQL HelmRelease instead
