apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system
  - apps/harbor
  - apps/keycloak
  - apps/kube-prometheus-stack
  - apps/minio-operator
  # apps/minio is deployed via flux-system/minio-tenant-ks.yaml
  # which waits for minio-operator to be ready first