apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minio-helmrepository.yaml
  - harbor-helmrepository.yaml
  - prometheus-community-helmrepository.yaml
  - bitnami-helmrepository.yaml
  - codecentric-helmrepository.yaml
