apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - harbor-helmrepository.yaml
  - forgejo-helmrepository.yaml
  - prometheus-community-helmrepository.yaml
  - bitnami-helmrepository.yaml
  - codecentric-helmrepository.yaml
  - grafana-helmrepository.yaml
  - opentelemetry-helmrepository.yaml
  - monitoring-config-ks.yaml
#  - minio-helmrepository.yaml
#  - minio-tenant-ks.yaml
  - arc-helm.yaml
