apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gotk-sync.yaml
  - minio-helmrepository.yaml
  - harbor-helmrepository.yaml
  - prometheus-community-helmrepository.yaml
  - minio-tenant-ks.yaml
  - metallb-helmrepository.yaml
  - metallb-config-ks.yaml
  - bitnami-helmrepository.yaml
