apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/k3s-cluster/apps/monitoring-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  dependsOn:
    - name: infra
  healthChecks:
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      name: harbor
      namespace: monitoring

