apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # PrometheusRules for alerting
  - prometheusrule-harbor.yaml
  - prometheusrule-nginx-ingress.yaml
  - prometheusrule-longhorn.yaml
  - prometheusrule-metallb.yaml
  # ServiceMonitors/PodMonitors for metrics scraping
  - servicemonitor-harbor.yaml
  - servicemonitor-nginx-ingress.yaml
  - servicemonitor-longhorn.yaml
  - servicemonitor-metallb.yaml

