apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - runner-namespace.yaml
  - operator-helmrelease.yaml
  - runner-scale-set-helmrelease.yaml
  - dependabot-runner-scale-set-helmrelease.yaml
  - code-quality-runner-helmrelease.yaml
  - modbus-runner-set.yaml
  - opcua-runner-set.yaml